version: "3.8"

services:
  aptd:
    depends_on: 
      postgres-db:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - dev-net
    environment: 
      - TERM=xterm-color
      - APTD__ENV=DEV

  postgres-db:
    restart: always
    networks:
      - dev-net
    
  adminer:
    image: adminer
    networks:
      - dev-net
    ports:
      - 8080:8080

networks:
  dev-net: