version: "3.8"

services:
  aptd:
    image: ${REGISTRY:-docker.io}/penikolov23/adastra-python-task-dockerized:${BUILD_TAG:-latest}

  postgres-db:
    image: postgres
    env_file:
      - database.env
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s 
      retries: 5
