services:
  aptd:
    image: penikolov23/adastra-python-task-dockerized
    environment:
      TERM: xterm-color
      APTD__ENV: PROD
      APTD__DATASOURCE: '1'
      APTD__DATASINK: "1\n(prod console)::key:{} | value:{} | ts:{}"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    networks:
      - prod-net

  aptd-postgresink:
    image: penikolov23/adastra-python-task-dockerized
    environment:
      APTD__ENV: PROD
      APTD__DATASOURCE: '1'
      APTD__DATASINK: "2\ndefault_schema\nuser\nuser\nsink-db\n5432"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 75M
    networks:
      - prod-net

  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: default_schema
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      prod-net:
        aliases:
          - sink-db

networks:
  prod-net:
    driver: overlay

volumes:
  postgres_prod_data:

