version: "3.8"

services:
  infrastructure-db:
    image: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s 
      retries: 5
    networks: 
      - infrastructure-net
    ports: 
      - "15432:5432"
    env_file: 
      - database.env
    volumes:
      - "./data/postgresql:/var/lib/postgresql"

  gogs:
    image: gogs/gogs
    depends_on: 
      infrastructure-db:
        condition: service_healthy
    networks: 
      - infrastructure-net
    ports: 
      - "10022:22"
      - "8081:3000"
    volumes:
      - "./data/gogs:/data"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    networks: 
      - infrastructure-net
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - "./data/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  # NOTE: this registry is not secure and must be marked as
  # insecure in the Docker engine's config
  local-registry:
    image: registry
    restart: always
    networks: 
      - infrastructure-net
    ports: 
      - "5000:5000"
    volumes: 
      - "./data/registry:/var/lib/registry"

networks: 
  infrastructure-net:
